name: langsync
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.4.0
  equatable: ^2.0.5
  hive: ^2.2.3
  http: ^1.1.0
  mason_logger: ^0.2.4
  pub_updater: ^0.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

executables:
  langsync:
